apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: sample-app-values
    namespace: sample-app
    files:
      - values.yaml=preprod-values.yaml
generatorOptions:
  disableNameSuffixHash: true
