replicaCount: 1

imagePullSecrets: []
nameOverride: "sample-app"
fullnameOverride: "sample-app"

serviceAccount:
  create: false

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources:
  phpfpm:
    limits:
      cpu: 400m
      memory: 800Mi
    requests:
      cpu: 400m
      memory: 800Mi
  nginx:
    limits:
      cpu: 100m
      memory: 400Mi
    requests:
      cpu: 100m
      memory: 400Mi

autoscaling:
  enabled: false

environments:
  APP_ENV: preprod
