on:
  workflow_run:
    workflows: [Release Drafter]
    types:
      - completed
    branches:
      - 'master'
    paths:
      - '!.kubernetes'
  push:
    branches:
      - '**'
      - '!master'
    paths:
      - '!.kubernetes'
  pull_request:
    types: [opened]

name: Workflow

env:
  IMAGE: 'sample-app'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-preprod-vulnerabilities-push:
    permissions:
      contents: 'write'
      id-token: 'write'
      checks: 'write'
      statuses: 'write'
      issues: 'write'
      pull-requests: 'write'
    timeout-minutes: 40
    runs-on: decathlon
    if: ${{  github.ref_type != 'tag' }}
    steps:
      - name: pre/post clean
        uses: dktunited/.github/actions/cleaner@main

      - uses: actions/checkout@v3

      - name: Set environment variables
        uses: dktunited/italy-reusable-github-workflow/actions/set-env@main
        with:
          environment: "PREPROD"

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: projects/${{ env.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/tools-ci/providers/github
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GCP_REGION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Generate Tag value
        if: github.ref == 'refs/heads/master'
        uses: dktunited/italy-reusable-github-workflow/actions/docker/generate-tag@main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: ${{ env.IMAGE }}
          target: php_prod
          load: true
          build-args: |
            GITHUB_TOKEN=${{ secrets.DKTUNITED_TOKEN }}
            VIRTUAL_REGISTRY=${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT }}/mirror

      - name: Tag image
        if: github.ref == 'refs/heads/master'
        uses: dktunited/italy-reusable-github-workflow/actions/docker/tag@main
        with:
          repository: '${{ env.GCP_REGION }}-docker.pkg.dev'
          gcp_project: '${{ env.GCP_PROJECT }}'
          image: ${{ env.IMAGE }}
          tag: ${{ env.TAG }}

      - name: Push image
        if: github.ref == 'refs/heads/master'
        uses: dktunited/italy-reusable-github-workflow/actions/docker/push@main
        with:
          repository: ${{ env.GCP_REGION }}-docker.pkg.dev
          gcp_project: ${{ env.GCP_PROJECT }}
          image: ${{ env.IMAGE }}
          tag: ${{ env.TAG }}

      - name: Clean old immages
        uses: 'docker://europe-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli'
        with:
          args: >-
            -repo=${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT }}/docker/${{ env.IMAGE }}
            -grace=48h
            -keep=5
            -tag-filter-any="^(develop|master|main)-[a-fA-F0-9]+-(?P<ts>.*)
